name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  schedule:
    - cron: '0 0 * * *' # nightly at 00:00 UTC

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ ubuntu-latest, windows-latest, macos-latest ]
        java: [ 17, 21 ]

    steps:
      - name: Checkout source
        uses: actions/checkout@v4

      - name: Set up JDK ${{ matrix.java }}
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: ${{ matrix.java }}
          cache: 'maven'

      - name: Cache local Maven repository
        uses: actions/cache@v4
        with:
          path: ${{ runner.home }}/.m2/repository
          key: ${{ runner.os }}-m2-${{ matrix.java }}-${{ hashFiles('**/pom.xml') }}
          restore-keys: ${{ runner.os }}-m2-${{ matrix.java }}-

      - name: Build and run tests
        run: mvn -B test

      - name: Upload test reports (artifact)
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: test-reports-${{ matrix.os }}-java${{ matrix.java }}
          path: target/surefire-reports/**/*.xml

      - name: Publish JUnit test reports to Checks
        if: always()
        uses: dorny/test-reporter@v1
        with:
          name: Unit tests
          path: target/surefire-reports/**/*.xml
          reporter: junit
          # do not fail the job if the reporter fails
          fail-on-error: false
